version: "3.8"
services:
  rvc-chat:
    image: rvc-chat:latest
    build:
      context: .
    container_name: RVC-Chat
    volumes:
      - ./models:/app/models
      - ./songs:/app/songs
      - .cache:/app/.cache
    ports:
      - 8501:8501
    stop_signal: SIGINT
    deploy:
      resources:
        reservations:
          cpus: ".999"
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]